from pydantic import BaseModel, Field
from typing import List, Optional

class Subtask(BaseModel):
    id: int = Field(..., description="Unique identifier for the subtask")
    description: str = Field(..., description="Detailed description of what needs to be done")
    expected_output: str = Field(..., description="What the expected output should look like")
    result: Optional[str] = Field(None, description="The actual result after execution")
    status: str = Field("PENDING", description="Status: PENDING, IN_PROGRESS, COMPLETED, or REJECTED")
    feedback: Optional[str] = Field(None, description="Feedback from the reviewer if rejected")

class Task(BaseModel):
    main_objective: str = Field(..., description="The main objective of the task")
    subtasks: List[Subtask] = Field(default_factory=list, description="List of subtasks generated by the planner")
    status: str = Field("PENDING", description="Overall status of the task")

class ReviewResult(BaseModel):
    approved: bool = Field(..., description="True if the result meets the requirements, False otherwise")
    feedback: str = Field(..., description="Detailed feedback on the result. If approved, can be brief. If rejected, must specify what needs to be fixed.")

class PlannerOutput(BaseModel):
    subtasks: List[Subtask] = Field(..., description="The breakdown of the main objective into manageable subtasks")
